stages:
  - build
  - ci-test
  - deploy
  - qa-test
  - callback
  - publish
  - tag

build_job:
    stage: build
    before_script:
      - echo $BUILD_TAGS
    script:
      - sed -i "s/BUILDVERSION/$BUILD_TAGS/g" debian/changelog
      - dpkg-buildpackage
      - mv ../*.deb /debs/
    only:
      - triggers
      - pipelines


add_tag:
    stage: tag
    before_script:
      - echo $BUILD_TAGS
    script:
      - git tag "$BUILD_TAGS" || true
      - git push --tags http://$ITP_GIT_USERNAME:$ITP_GET_PASSWD@git.fangod.com/pro/project.git HEAD:master
    only:
      - triggers
      - pipelines
